x-container: &container
  ulimits:
    nofile:
      soft: ${NOFILE_SOFT_LIMIT:-65535}
      hard: ${NOFILE_HARD_LIMIT:-65535}
  restart: ${RESTART_POLICY:-unless-stopped}
  security_opt:
    - no-new-privileges:true
  tmpfs:
    - /tmp:noexec,nosuid,size=50m
  env_file:
    - ".env"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: ${LOGGING_MAX_SIZE:-5M}
      max-file: ${LOGGING_COUNT_FILES:-10}

x-network: &network
  networks:
    - all-net

services:
  haproxy:
    <<: [*container, *logging, *network]
    image: ghcr.io/adam-sizzler/haproxy:latest
    container_name: haproxy
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      # HAPROXY_CERT_PATH: ${HAPROXY_CERT_PATH:-/etc/haproxy/certs/${DOMAIN_NAME}.pem}
    ports:
      - "${HAPROXY_EXTERNAL_PORT:-443}:443"
    volumes:
      - haproxy-data:/etc/haproxy/data
      - haproxy-socket:/var/run/haproxy
      # - certificate:/etc/haproxy/certs:ro
    healthcheck:
      test: ["CMD", "pidof", "haproxy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  haproxy-data:
    name: haproxy-data
    driver: local
  haproxy-socket:
    name: haproxy-socket
    driver: local
  certificate:
    name: certificate
    driver: local

networks:
  all-net:
    driver: bridge
